# Generated by Django 5.1.1 on 2024-09-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialservice',
            options={'ordering': ['created_at']},
        ),
    ]
