# Generated by Django 5.1.1 on 2024-10-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_skills_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AddField(
            model_name='team',
            name='telegram',
            field=models.CharField(default='#', max_length=220),
        ),
    ]
