# Generated by Django 5.1.1 on 2024-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_descripton_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='services'),
        ),
    ]
